studentreg/force-app/main/default/objects/Album__c/Album__c.object-meta.xml
<CustomObject>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

studentreg/force-app/main/default/objects/Songs__c/Songs__c.object-meta.xml
<CustomObject>
    <label>Songs</label>
    <nameField>
        <label>Songs Name New1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

studentreg/force-app/main/default/objects/Songs__c/fields/Album__c.field-meta.xml
<CustomField>
    <fullName>Album__c</fullName>
    <label>Album</label>
    <referenceTo>Album__c</referenceTo>
    <relationshipLabel>Songs</relationshipLabel>
    <relationshipName>Songs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

studentreg/force-app/main/default/classes/SongsDisplayHandlerTest.cls
@isTest
private class SongsDisplayHandlerTest{
    
    static testmethod void executeRun(){
        
        Album__c album = new Album__c();
        album.Name = 'test';
        album.Author__c = 'test';
        insert album;
        
        Songs__c song = new Songs__c();
        song.Album__c = album.Id;
        song.Name = 'test';
        song.Title__c = 'test';
        insert song;
        
        SongsDisplayHandler.fetchDetails();
        new SongsDisplayHandler().getNextSong();
        new SongsDisplayHandler().peekQueue();
        new SongsDisplayHandler().setSongs(null);
        
    }
    
}